#!/usr/bin/env python

from gpu_utils import nvidia_smi
from subprocess import run, PIPE
import re

gpu_info = nvidia_smi()
pid_matcher = re.compile("\|\s+\d\s+(\d+)")  # just by inspection; PID lines start "|    gpu_id    pid"
pids = re.findall(pid_matcher, gpu_info)

print(gpu_info)

try:
    # just want to print the headers once
    print(run(["ps", "u", pids[0]], stdout=PIPE).stdout.decode(), end="")

    for pid in pids[1:]:
        print(run(["ps", "--no-headers", "u", pid], stdout=PIPE).stdout.decode(), end="")
except IndexError:  # no pids
    pass
